config/routes.rb
Rails.application.routes.draw do
  get 'weigh_ins/show'

  get 'weigh_ins/index'

  get 'weigh_ins/edit'

  get 'weigh_ins/new'

  get 'menu/show'

  devise_for :users
  get 'exercises/index'

  get 'exercises/show'

  post 'exercises/new'

  get 'journal_entries/show'

  get 'select_date', to: 'journal_entries#select_date', as: :select_date

  get 'search', to: 'exercises#search', as: :exercise_search

  get 'edit_goals/:id', to: 'users#edit_goals', as: :edit_goals

  put 'update_goals/:id', to: 'users#update_goals', as: :update_goals

  resources :exercises, :journal_entries, :exercise, :food_entries, :users, :weigh_ins

  root 'journal_entries#select_date'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :journal_entry
end

app/models/food_entry.rb
class FoodEntry < ActiveRecord::Base
end

app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
  has_many :exercises
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :weigh_in
end

app/models/weigh_in.rb
class WeighIn < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
require 'date'

class ExercisesController < ApplicationController
  attr_accessor :journal_entry_id, :date, :exercise
  def index
  end

  def show
  end

  def search
    @journal_entry = JournalEntry.find(params[:journal_entry_id])
    @exercise      = Exercise.new(user_id: current_user.id)
    @date          = params[:date]
  end

  def new
    @last_session  = Exercise.where(exercise: params[:exercise], user_id: current_user.id).last
    @exercise      = Exercise.where(exercise: params[:exercise], user_id: current_user.id).last
    @exercise      ||= Exercise.new(exercise: params[:exercise], user_id: current_user.id)
    @exercise.date = params[:date]
  end

  def edit
    @exercise = Exercise.find(params[:id])
  end

  def update
    @exercise = Exercise.find(params[:id])
    @exercise.update(exercise_params)
    @exercise.save
    @journal_entry = JournalEntry.find_by(date: @exercise.date, user_id: current_user.id)
    @exercise.update(journal_entry_id: @journal_entry.id)
    @exercise.save

    redirect_to select_date_path(date: @journal_entry.date)
  end

  def create
    @exercise = Exercise.create(exercise_params)
    @exercise.save
    @journal_entry = JournalEntry.find_by(date: @exercise.date, user_id: current_user.id)
    @exercise.update(journal_entry_id: @journal_entry.id, user_id: current_user.id)
    @exercise.save

    redirect_to select_date_path(date: @journal_entry.date)
  end

  def destroy
    @exercise      = Exercise.find(params[:id])
    @journal_entry = JournalEntry.find(@exercise.journal_entry_id)
    @exercise.destroy

    redirect_to select_date_path(date: @journal_entry.date)
  end

  private
  def exercise_params
    params.require(:exercise).permit(:date, :exercise, :weight_in_lbs, :reps, :sets, :notes)
  end
end

app/controllers/food_entries_controller.rb
class FoodEntriesController < ApplicationController
  def show
  end

  def new
    @food_entry = FoodEntry.new(date: params[:date])
    @journal_entry = JournalEntry.find(params[:journal_entry_id])
  end

  def create
    @food_entry = FoodEntry.create(food_entry_params)
    @food_entry.update(journal_entry_id: params[:journal_entry_id])
    @food_entry.save
    @journal_entry = JournalEntry.find(params[:journal_entry_id])

    redirect_to select_date_path(date: @journal_entry.date)
  end

  def edit
    @food_entry = FoodEntry.find(params[:id])
  end

  def update
    @food_entry = FoodEntry.find(params[:id])
    @food_entry.update(food_entry_params)
    @food_entry.save

    redirect_to select_date_path(date: @food_entry.date)
  end

  def index
  end
  
  def destroy
    @food_entry = FoodEntry.find(params[:id])
    @date = @food_entry.date
    @food_entry.destroy

    redirect_to select_date_path(date: @date)
  end

  private
  def food_entry_params
    params.require(:food_entry).permit(:name, :calories_per_serving, :protien_per_servings, :carbohydrates_per_serving, :fat_per_serving, :sugar_per_serving, :servings, :date)
  end
end

app/controllers/journal_entries_controller.rb
require 'date'

class JournalEntriesController < ApplicationController
  def show
    @journal_entry      = JournalEntry.find(params[:id])
    @exercises          = Exercise.where(journal_entry_id: @journal_entry.id)
    @weigh_in           = WeighIn.find_by(date: @journal_entry.date, user_id: current_user.id)
    puts "Weigh in: #{@weigh_in} ****************"
    @food_entries       = FoodEntry.where(journal_entry_id: @journal_entry.id)
    @calorie_total      = calorie_total(@food_entries)
    @daily_calorie_goal = daily_calorie_goal
    @calories_left      = @daily_calorie_goal - @calorie_total
  end

  def select_date
    if current_user.nil?
      redirect_to new_user_session_path
    else
      date = params[:date]
      date ||= Date.today

      redirect_to journal_entry_path(
        find_or_create_journal_entry(date))
    end
  end

  private

  def find_or_create_journal_entry date
    journal_entry = JournalEntry.find_by(date: date, user_id: current_user.id)
    journal_entry ||= JournalEntry.create(date: date, user_id: current_user.id)
  end

  def calorie_total food_entries
    calorie_total = food_entries.sum(:calories_per_serving)
    calorie_total ||= 0
  end

  def daily_calorie_goal
    daily_calorie_goal = User.find(current_user.id).daily_calorie_goal
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def index
  end

  def edit
  end

  def edit_goals
    @user = User.find(current_user.id)
  end

  def update_goals
    @user = User.find(current_user.id)
    @user.update(goals_params)
    @user.save

    redirect_to menu_show_path
  end

  private
  def goals_params
    params.require(:user)
      .permit(:starting_weight_in_lbs, :current_weight_in_lbs, :goal_weight_in_lbs, :weekly_goal_weight_loss_in_lbs, :activity_level, :daily_calorie_goal)
  end
end

app/controllers/weigh_ins_controller.rb
class WeighInsController < ApplicationController
  attr_accessor :weight_in_lbs, :date
  def show
    
  end

  def index
  end

  def edit
  end

  def new
    @weigh_in = WeighIn.new(user_id: current_user.id, date: params[:date])
  end

  def create
    @weigh_in = WeighIn.create(user_id: current_user.id, date: params[:date], weight_in_lbs: weigh_in_params[:weight_in_lbs])

    redirect_to select_date_path(date: @weigh_in.date)
  end

  private

  def weigh_in_params
    params.require(:weigh_in).permit(:weight_in_lbs, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/food_entries_helper.rb
module FoodEntriesHelper
end

app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

app/helpers/menu_controller_helper.rb
module MenuControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weigh_ins_helper.rb
module WeighInsHelper
end

app/views/exercises/_last_session.html.erb
<% if @last_session.nil? %>
  <p> You've never done this exercise before </p>
<% else %>
  <p class="last-session">On <%= @last_session.date %> you did <%= @last_session.exercise %>.
  <%= @last_session.sets %> sets of <%= @last_session.reps %> with <%= @last_session.weight_in_lbs %>lbs.
  Notes: <%= @last_session.notes %></p>
<% end %>

app/views/exercises/_new.html.erb
<%= form_for @exercise, url: exercises_path, method: :post do |form| %>
    <%= form.text_field :exercise, class: "new-input", placeholder: "Exercise" %>
    <%= form.text_field :weight_in_lbs, class: "new-input", placeholder: "Weight In Lbs" %>
    <%= form.text_field :sets, class: "new-input", placeholder: "Sets" %>
    <%= form.text_field :reps, class: "new-input", placeholder: "Reps" %>
    <div>
    <%= form.date_select :date, class: "new-exercise-date-select", placeholder: "Date" %>
    </div>
    <%= form.text_area :notes, class: "new-exercise-text-area", placeholder: "Notes" %>
    <%= form.submit "Submit Exercise", class: "submit" %>
<% end %>

app/views/exercises/edit.html.erb
<h2 class="edit-entry">Edit Entry</h2>
<%= form_for @exercise, url: exercise_path, method: :put do |form| %>
    <%= form.text_field :exercise, class: "new-input", placeholder: "Exercise" %>
    <%= form.text_field :weight_in_lbs, class: "new-input", placeholder: "Weight In Lbs" %>
    <%= form.text_field :sets, class: "new-input", placeholder: "Sets" %>
    <%= form.text_field :reps, class: "new-input", placeholder: "Reps" %>
    <div>
    <%= form.date_select :date, class: "new-date-select", placeholder: "Date" %>
    </div>
    <%= form.text_area :notes, class: "new-exercise-text-area", placeholder: "Notes" %>
    <%= form.submit "Submit", class: "submit" %>
<% end %>

app/views/exercises/new.html.erb
<div class="exercise-new">
  <h2>Add Entry</h2>
  <%= render "last_session", locals: { last_session: @last_session } %>
  <%= render "new", locals: { exercise: @exercise } %>
</div>

app/views/exercises/search.html.erb
<%= form_tag exercises_new_path(date: @date), class: "search-exercise"  do %>
  <h2 class="search-title">What exercise are you doing?</h2>
  <%= text_field_tag :exercise, nil, placeholder: "Search for an exercise" %>

  <%= submit_tag 'Search Exercise', class: "submit" %>
<% end %>

app/views/food_entries/edit.html.erb
<h2 class="edit-entry">Edit Entry</h2>
<%= form_for @food_entry, url: food_entry_path, method: :put do |form| %>
    <%= form.text_field :name, class: "new-input", placeholder: "Name" %>
    <%= form.text_field :calories_per_serving, class: "new-input", placeholder: "Calories" %>
    <%= form.text_field :protien_per_servings, class: "new-input", placeholder: "Protien" %>
    <%= form.text_field :carbohydrates_per_serving, class: "new-input", placeholder: "Carbs" %>
    <%= form.text_field :fat_per_serving, class: "new-input", placeholder: "Fat" %>
    <%= form.text_field :sugar_per_serving, class: "new-input", placeholder: "Sugar" %>
    <%= form.text_field :servings, class: "new-input", placeholder: "Servings" %>
    <div>
    <%= form.date_select :date, class: "new-date-select", placeholder: "Date" %>
    </div>
    <%= form.submit "Submit", class: "submit" %>
<% end %>

app/views/food_entries/index.html.erb
<h1>FoodEntries#index</h1>
<p>Find me in app/views/food_entries/index.html.erb</p>

app/views/food_entries/new.html.erb
<h1 class="search-title">New Entry</h1>

<%= form_for @food_entry, url: food_entries_path(journal_entry_id: @journal_entry.id), method: :post do |form| %>
    <%= form.text_field :name, class: "new-input", placeholder: "  Food name" %>
    <%= form.text_field :servings, class: "new-input", placeholder: "  Servings" %>
    <%= form.text_field :calories_per_serving, class: "new-input", placeholder: "  Calories per serving" %>
    <%= form.text_field :protien_per_servings, class: "new-input", placeholder: "  Protien per serving" %>
    <%= form.text_field :carbohydrates_per_serving, class: "new-input", placeholder: "  Carbs per serving" %>
    <%= form.text_field :fat_per_serving, class: "new-input", placeholder: "  Fat per serving" %>
    <%= form.text_field :sugar_per_serving, class: "new-input", placeholder: "  Sugar per serving" %>
    <div>
    <%= form.date_select :date, class: "", placeholder: "Date" %>
    </div>
    <%= form.submit "Submit Food Entry", class: "submit" %>
<% end %>

app/views/food_entries/show.html.erb
<h1>FoodEntries#show</h1>
<p>Find me in app/views/food_entries/show.html.erb</p>

app/views/journal_entries/_exercise_entry_show.html.erb
  <h3 class="exercise">Exercises</h3>
  <% @exercises.each do |exercise| %>
    <div class="exercise-details">

      <%= link_to edit_exercise_path(exercise) do %>
        <div class="exercise-row">
          <strong><%= exercise.exercise %></strong>
          <p class="e-r-contents">
            Sets: <%= exercise.sets %>, Reps: <%= exercise.reps %>, Lbs: <%= exercise.weight_in_lbs %>
          </p>
          <p class="e-r-contents">
            <%= link_to image_tag("trash-icon", class: "trash-icon"), exercise_path(exercise), method: :delete, class: "destroy-link" %>
          </p>
        </div>
        <p class="large-row exercise-row">
          Notes:
          <%= exercise.notes %>
        </p>
      <% end %>
    </div>
  <% end %>

  <%= link_to '+ Add Exercise', exercise_search_path(journal_entry_id: @journal_entry.id, date: @journal_entry.date), class: "link" %>

app/views/journal_entries/_food_entry_show.html.erb
<div class="category-header"><h3 class="exercise">Food</h3><p><%= @calorie_total %></p></div>

<div class="exercises">
  <% if @food_entries %>
    <% @food_entries.each do |fe| %>
    <div class="exercise-details">
      <%= link_to edit_food_entry_path(fe) do %>
        <div class="exercise-row">
        <strong><%= fe.name %></strong>
        <p class="e-r-contents" >
          Calories: <%= fe.calories_per_serving %>,
          Protien: <%= fe.protien_per_servings %>,
          Carbs: <%= fe.carbohydrates_per_serving %>,
          Fat: <%= fe.fat_per_serving %>,
          Servings: <%= fe.servings %>
          </p>

          <p class="e-r-contents">
            <%= link_to image_tag("trash-icon", class: "trash-icon"), food_entry_path(fe), method: :delete, class: "destroy-link" %>
          </p>
        <% end %>
      </div>
    </div>
    <% end %>
  <% else %>
    <p>No food entries today.</p>
  <% end %>
  <%= link_to '+ Add Food', new_food_entry_path(journal_entry_id: @journal_entry.id, date: @journal_entry.date), class: "link" %>
</div>

app/views/journal_entries/_weigh_in_show.html.erb
<div class="category-header"><h3 class="exercise">Daily Weigh In</h3></div>

<div class="exercises">
  <% if @weigh_in %>
    <div class="exercise-details">
      <div class="exercise-row">
        <p>
          <%= @weigh_in.weight_in_lbs %>lbs
        </p>
      </div>
      </div>
  <% else %>
    <%= link_to "+ Weigh In", weigh_ins_new_path(date: @journal_entry.date), class: "link" %>
  <% end %>
</div>

app/views/journal_entries/show.html.erb
<%= link_to "...", menu_show_path, method: :get, class: "menu-icon" %>

<div class="journal-header">
  <%= link_to image_tag("left-arrows-2x.png", class: "arrow" ), select_date_path(date: @journal_entry.date - 1.day) %>
  <h1 class="header"><%= @journal_entry.date %></h1>
  <%= link_to image_tag("right-arrows-2x copy.png", class: "arrow"), select_date_path(date: @journal_entry.date + 1.day) %>
</div>

<div class="calorie-summary">
  <strong>Calories Remaining</strong>
  <div><div><%= @daily_calorie_goal %> <p>Goal</p></div> - <div><%= @calorie_total %><p>Food</p></div> = <div><strong><%= @calories_left %></strong><p>Remaining</p></p></div></div>
</div>

<div class="exercises">
  <%= render "exercise_entry_show", locals: { exercises: @exercises, journal_entry: @journal_entry } %>
  <%= render "food_entry_show", locals: { food_entries: @food_entries, calorie_total: @calorie_total } %>
  <%= render "weigh_in_show", locals: { weigh_in: @weigh_in, journal_entry: @journal_entry } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FitnessBuddy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/menu/show.html.erb
<div id="menu">
  <div id="menu-header">
    <%= link_to image_tag("left-arrows-2x", id: "menu-arrow"), select_date_path(date: Date.today) %>
    <h1>Menu</h1>
    <h2><%= @user.email %></h2>
  </div>

  <div id="menu-list">
    <%= link_to "Goals", edit_goals_path(current_user.id), method: :get, class: "sign-out" %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "sign-out" %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/edit_goals.html.erb
<h2 class="edit-entry">Update Goals</h2>
<%= form_for @user, url: update_goals_path(@user), method: :put do |form| %>
    <%= form.text_field :starting_weight_in_lbs, class: "new-input", placeholder: "Starting Weight" %>
    <%= form.text_field :current_weight_in_lbs, class: "new-input", placeholder: "Current Weight" %>
    <%= form.text_field :goal_weight_in_lbs, class: "new-input", placeholder: "Goal Weight" %>
    <%= form.text_field :weekly_goal_weight_loss_in_lbs, class: "new-input", placeholder: "Weekly Goal Weight Loss" %>
    <%= form.text_field :activity_level, class: "new-input", placeholder: "Activity Level" %>
    <%= form.text_field :daily_calorie_goal, class: "new-input", placeholder: "Daily Calorie Goal" %>
    <div>
    </div>
    <%= form.submit "Submit", class: "submit" %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/weigh_ins/edit.html.erb
<h1>WeighIns#edit</h1>
<p>Find me in app/views/weigh_ins/edit.html.erb</p>

app/views/weigh_ins/index.html.erb
<h1>WeighIns#index</h1>
<p>Find me in app/views/weigh_ins/index.html.erb</p>

app/views/weigh_ins/new.html.erb
<%= form_for @weigh_in, url: weigh_ins_path(date: @weigh_in.date), method: :post do |form| %>
    <%= form.text_field :weight_in_lbs, class: "new-input", placeholder: "Weight In Lbs" %>
    <div>
    <%= form.date_select :date, class: "new-exercise-date-select", placeholder: "Date" %>
    </div>
    <%= form.submit "Submit Weigh In", class: "submit" %>
<% end %>

app/views/weigh_ins/show.html.erb
<h1>WeighIns#show</h1>
<p>Find me in app/views/weigh_ins/show.html.erb</p>